### ISSUE TITLE
Plot scheduler throughput and latencies on perf-dash

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/perf-tests#132]
With some recent changes, we've now started to capture scheduler metrics ([e.g](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/167/artifacts/SchedulingMetrics_density_2018-06-15T23:31:48Z.json)) in our scalability tests. We need to plot those values over time.

cc @kubernetes/sig-scalability-misc @kubernetes/sig-scheduling-misc 

/assign @krzysied 
Krzysiek - Would you be able to take this up?

**Comment by krzysied** [comment]
@shyamjvs - Sure.

**Comment by shyamjvs** [comment]
One more thing - could you merge `SchedulerLatency` and `SchedulerThroughput` dashboards into a single one named `SchedulerMetrics` and have the individual metrics split by labels? Let me reopen this issue so we don't forget to do that.

**Comment by krzysied** [comment]
> One more thing - could you merge SchedulerLatency and SchedulerThroughput dashboards into a single one named SchedulerMetrics and have the individual metrics split by labels? Let me reopen this issue so we don't forget to do that.

TBH, I'm not a fan of this idea. SchedulerLatency and SchedulerThroughput are two separate metrics and in my opinion they shouldn't be merged.
Currently, we divide results into two-level groups - <job_name; metric_name>. Merging SchedulerLatency and SchedulerThroughput doesn't translate well to these assumed groups. Merging these metrics will result in SchedulerThroughput having additional dimension labels (from SchedulerLatency) available.

Maybe instead of merging those metrics, we want to create different grouping - for example <job_name;metrics_group_name;specific_metric_name>.

@shyamjvs Let me know what you think about it.

**Comment by shyamjvs** [comment]
I guess this has been discussed offline and it's clear now what I was suggesting (i.e not merging both plots into one single graph, but just split them into SchedulerMetrics category).

I'm closing this issue with all the needed changes in. Scheduler latency and throughput metrics are now available on perf-dash.k8s.io
Thanks @krzysied.
