### ISSUE TITLE
pull-perf-tests-verify-lint fails (almost) consistently due to timeouts

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1469]
![7HaMwVy9xQvWMhy](https://user-images.githubusercontent.com/2604887/93179527-1290de00-f736-11ea-8f25-b77e0eac1624.png)

Example PR with failure - https://github.com/kubernetes/perf-tests/pull/1464
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/perf-tests/1464/pull-perf-tests-verify-lint/1305501029361520640

**Comment by mm4tt** [comment]
Assigning to the current scalability oncall

**Comment by tosi3k** [comment]
Strange, the only recent change I noticed related to that job is https://github.com/kubernetes/test-infra/pull/19120 where we set the explicit resource requests and limits. It was submitted on the day we started experiencing consistent failures due to those timeouts (September 9th).

There were also changes to the `.golangci.yml` configuration file in https://github.com/kubernetes/perf-tests/pull/1426 and https://github.com/kubernetes/perf-tests/pull/1446 but they were submitted 2 weeks ago and seem to be unrelated.

Could we lack resources for that job? This is quite odd, as one would expect that the current limits are more than enough.

**Comment by mm4tt** [comment]
Dunno, we can try bumping the resource (or timeout) to see if it helps? Would you mind sending a PR?

**Comment by kushthedude** [comment]
That is odd as generally the lint job completes under <10 min and golangci-lint doesn't need much overhead, seeing from the above failures the job ran for 42 minutes and then timed out.

**Comment by tosi3k** [comment]
Bumping up from 1 to 2 CPUs has lowered the job execution time from 42 mins to almost 9 ([link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/perf-tests/1473/pull-perf-tests-verify-lint/1306234458470354944)), so indeed the CPU was the issue here. We can either further increase the CPU limit for the job (local executions of `make verify-lint` have shown me the peak CPU usage of 3.5) or leave it as it is and just increase the timeout limit in `golangci.yml` as in my experimental PR https://github.com/kubernetes/perf-tests/pull/1473.

**Comment by mm4tt** [comment]
Leaving 2vCPUs and increasing the timeout makes sense, thanks!
