### ISSUE TITLE
CL2 image-preload feature doesn't work with containerd CRI

### ISSUE THREAD

**Issue by hanamantagoudvk** [kubernetes/perf-tests#1619]
**What happened**:

node-preload-images option fails to pre-load the images to all the nodes in the cluster.

**What you expected to happen**:

When node-preload-images option is used , it should pre-load the images before starting the testcases.

**How to reproduce it (as minimally and precisely as possible)**:

There are two ways to reproduce this problem:

1) By directly applying daemonset yaml file (with any image-name hardcoded inside).

kubectl apply -f /home/k8s/go/src/k8s.io/perf-tests/clusterloader2/pkg/imagepreload/manifests/daemonset.yaml

2) When we run clusterloader2 testcases as shown below

a) 

/home/k8s/go/src/k8s.io/perf-tests/clusterloader2/run-e2e.sh --provider=local --kubeconfig=$HOME/.kube/config --testsuite=/home/k8s/go/src/k8s.io/perf-tests/clusterloader2/testing/network/suite.yaml 
--node-preload-images=vivekthrivikraman/netperfbenchmark:0.01

b) vivekthrivikraman/netperfbenchmark:0.01 image is present in docker hub and we expect it to get downloaded using "docker pull vivekthrivikraman/netperfbenchmark:0.01" command

c) But we see the following error with preload pods 

root@k8s:~# kubectl get pods --all-namespaces
preload              preload-d4nqt                                0/1     Init:CrashLoopBackOff   3          64s
preload              preload-hgvzc                                0/1     Init:CrashLoopBackOff   3          64s
preload              preload-ngkt5                                0/1     Init:CrashLoopBackOff   3          64s
root@k8s:~#

root@k8s:~# kubectl describe pod preload-d4nqt -n preload
Name:         preload-d4nqt
Namespace:    preload
Priority:     0
Node:         kind-worker2/172.18.0.5
Start Time:   Fri, 27 Nov 2020 19:50:24 +0530
Labels:       controller-revision-hash=6c7bc9d988
              name=preload
              pod-template-generation=1
Annotations:  cni.projectcalico.org/podIP: 10.168.110.147/32
              cni.projectcalico.org/podIPs: 10.168.110.147/32
              k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "ips": [
                        "10.168.110.147"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "ips": [
                        "10.168.110.147"
                    ],
                    "default": true,
                    "dns": {}
                }]
Status:       Pending
IP:           10.168.110.147
IPs:
  IP:           10.168.110.147
Controlled By:  DaemonSet/preload
Init Containers:
  preload-1:
    Container ID:  containerd://4c31e1d266d63049ab7672780e7d3f50ec9469dd11152550f6f60879457607dd
    Image:         docker
    Image ID:      docker.io/library/docker@sha256:9170b902404a630a982a2a6473442d3e2cc2342b66345f7a9cf148f8affcf5d3
    Port:          <none>
    Host Port:     <none>
    Command:
      docker
      pull
      vivekthrivikraman/netperfbenchmark:0.01
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 27 Nov 2020 19:51:03 +0530
      Finished:     Fri, 27 Nov 2020 19:51:03 +0530
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 27 Nov 2020 19:50:39 +0530
      Finished:     Fri, 27 Nov 2020 19:50:39 +0530
    Ready:          False
    Restart Count:  3
    Environment:    <none>
    Mounts:
      /var/run from docker (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xzrtg (ro)
Containers:
  pause:
    Container ID:
    Image:          gcr.io/google_containers/pause
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xzrtg (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  docker:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run
    HostPathType:
  default-token-xzrtg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xzrtg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason          Age               From               Message
  ----     ------          ----              ----               -------
  Normal   Scheduled       47s               default-scheduler  Successfully assigned preload/preload-d4nqt to kind-worker2
  Normal   AddedInterface  47s               multus             Add eth0 [10.168.110.147/32]
  Normal   Pulled          9s (x4 over 47s)  kubelet            Container image "docker" already present on machine
  Normal   Created         9s (x4 over 47s)  kubelet            Created container preload-1
  Normal   Started         9s (x4 over 47s)  kubelet            Started container preload-1
  Warning  BackOff         9s (x5 over 45s)  kubelet            Back-off restarting failed container
root@k8s:~#

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

root@k8s:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
root@k8s:~#

- Cloud provider or hardware configuration:  
KIND k8s cluster on laptop

- OS (e.g: `cat /etc/os-release`):

root@k8s:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):

root@k8s:~# uname -a
Linux k8s 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@k8s:~#

**Comment by wojtek-t** [comment]
@mm4tt - FYI

**Comment by mm4tt** [comment]
Sorry for the delay. Busy week. 

IIRC, the image-preloading functionality was implemented in CL2 but we didn't enable it anywhere. It may not work. Let me check this

**Comment by mm4tt** [comment]
My guess is that it doesn't work because it's based on docker pull while we don't use docker anymore on nodes (we switched to containerd). 
I'll try to get it working in our tests. 

@hanamantagoudvk, could you dump here logs for the failing image-preload init container? I.e. `kubectl logs ...`

**Comment by hanamantagoudvk** [comment]
I get the following error , when i try to get the logs of init conainer "preload-1" , pod : preload-bt5tl

root@k8s:~# kubectl logs preload-bt5tl -c preload-1 -n preload
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

root@k8s:~# kubectl get pods --all-namespaces
....
....
...
preload              preload-bt5tl                                0/1     Init:CrashLoopBackOff   6          7m2s
preload              preload-c9jqk                                0/1     Init:CrashLoopBackOff   6          6m50s
preload              preload-htqrz                                0/1     Init:CrashLoopBackOff   6          6m37s
root@k8s:~#

**Comment by mm4tt** [comment]
Ok, I managed to reproduce the same error in our presubmit in https://github.com/kubernetes/perf-tests/pull/1625.
The image preload fails with: `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` [example log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/perf-tests/1625/pull-perf-tests-clusterloader2/1334185724596981760/artifacts/e2e-1625-62db2-minion-group-0pvn/cl2-image-preload-0.log)

This is because we migrated to containerd and docker is no longer available on the nodes.

Let me update the issue to reflect that and propose some steps to fix it.

**Comment by mm4tt** [comment]
/good-first-issue

### Repro

1. The failure is reproduced in https://github.com/kubernetes/perf-tests/pull/1625. Use it as a base for further debugging / experiments

### How to fix

We need to replace the usage of docker in the [image-preload daemonset](https://github.com/kubernetes/perf-tests/blob/4f3e551abf27b8df5fcde0a0c547579ed9be10aa/clusterloader2/pkg/imagepreload/manifests/daemonset.yaml) with containerd
   1. Instead of calling `docker pull` we should be calling `ctr image pull`
   2. The [docker](https://hub.docker.com/_/docker) image that we use should be replaced with an image that contains the `ctr` binary. We can either look for an existing image (I couldn't find anything at a first glance) or build something ourselves (image with sh + ctr installed manually should be all we need). If we going to build image on our own, we should put the docker file in the [util-images](https://github.com/kubernetes/perf-tests/tree/c8098dfa0d3c09becd3f669b9ba2b49e413c5bda/util-images) dir. You can find some examples there as well.
   3. The `ctr` from the container should connect to the `containerd` daemon on the host via the `/var/run/containerd/conainerd.sock` file. This means that probably all we need to do is to mount the `/var/run` dir from the host in the container, which we already do for docker. So probably no change here, but I wouldn't bet my life on it.
   4. Once we figure out how to make it work for containerd, we should make the change backward compatible, i.e. we should retain the docker support.  We can have some gating logic that would be either using docker or containerd based on some flag or env variable. 


If there is someone willing to help I will be more than happy to guide and review.

**Comment by lyzs90** [comment]
@vasanth-ks hows progress on your end? i'm hoping to see this through so we can unblock https://github.com/kubernetes/kubernetes/issues/90833

**Comment by lyzs90** [comment]
@mm4tt I'll follow up on this one

**Comment by vasanth-ks** [comment]
Sorry for the delayed response. Been a little busy. I am working with Matt on this issue to try to build and push containerd image to docker hub. Have not been successful yet.

**Comment by mm4tt** [comment]
I believe we can close this one. Fixed in https://github.com/kubernetes/perf-tests/pull/1654
