### ISSUE TITLE
ClusterLoader2 - Steady State Tests

### ISSUE THREAD

**Issue by melnikalex** [kubernetes/perf-tests#1880]
**What would you like to be added**:
I want to run "steady-state" tests on kubernetes clusters to be able to compare regressions in clusters in context of different failure modes.

Some examples:
* Create deployments/secrets/configmaps for 6 hours
* Delete deployments/secrets/configmaps for 6 hours
* List deployments/secrets/configmaps for 6 hours

Obviously it wouldn't be wise to just create a resource for 6 hours with out a corresponding delete, so users will have craft their configs accordingly.

**Why is this needed**:
It's difficult to test performance regression in conjunction with other infrastructure events. For example, comparing performance in a cluster during cluster upgrades. Say I run a [load test](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/load/config.yaml) during a 1.21 -> 1.22 upgrade on 2 clusters, and 1 cluster sees a lot more 5XX apiserver errors during the upgrade, I can't confidently say that that cluster has worse performance. The worse performance could've just been a lucky alignment of a particular step in the clusterlaoder test and a step in the cluster update.

**Why is this needed**:

**Comment by shyamjvs** [comment]
@wojtek-t @mm4tt Maybe something like the above already exists?

**Comment by melnikalex** [comment]
Added a quick PR that highlights what I'm personally looking for. Feel free to use it as inspiration, but I'm not attached to it in anyway and open to other approaches.

**Comment by mm4tt** [comment]
I'm leaving it to Marcel, but my 2cents is that what you're asking for is kind of against the CL2 test API. The current idea behind the API is that you provide a "state the cluster should be in", via the phase step, and CL2 brings cluster to that state. IIUC what you're asking for, you'd like to have CL2 to execute some sequence of operations on the cluster for a provided time. This use-case might be valid, but if we want to support it, we should make it in a way that will keep our API consistent. 

Just thinking out loud, but maybe instead of playing with tuning sets we should provide an option to execute given step or module N times. Then you could execute the "scale up/down" module (that @shyamjvs mentioned above) for M hours and it would generate a steady churn on the cluster. Would it work for you?

**Comment by wojtek-t** [comment]
I agree with Matt here.

I think that what we're missing is exactly what @mm4tt described above, which is in the Phase API add some "repeat config" (we need a better name though):
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/api/types.go#L104

That would allow us to repeat certain things N times, for N hours or sth like that.
