### ISSUE TITLE
CL2 doesn't distinguish between single pod and collection of pods deletion in api-latency measurement

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1908]
For example, a test can fail with:

```
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheus error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:events Subresource: Verb:DELETE Scope:namespace Latency:perc50: 33.374999999s, perc90: 38.74s, perc99: 39.873999999s Count:11 SlowCount:10}; expected perc99 <= 1s]]
```

The scope is namespaces, so it's actually a DELETECOLLETION call which shouldn't be a subject for 1s time limit.

In addition, the grafana dashboards should be changed to reflect this distinction. We should have separate graphs for resource level mutations (1s limit) and separate for collection mutations.

**Comment by azylinski** [comment]
I believe this could be fixed now. Few points:
 1) https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go#L407-L415 - this is incorrect - as mentioned in the title, the `DELETECOLLECTION` (which maps to `verb:DELETE scope:namespace`) should have `30s` threashold - in other words, there should be a simple, 1-1 mapping from scope to threashold
 2) https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go#L43 - this should be updated to 30s , to reflect current SLO definition (it was recently updated)
 3) for `v1.23+` we should use `apiserver_request_slo_duration_seconds` metric instead of `apiserver_request_duration_seconds` (which includes admission_webhooks)
