### ISSUE TITLE
Move performance-related e2e tests to this repo

### ISSUE THREAD

**Issue by gmarek** [kubernetes/perf-tests#4]
Is is currently possible to have e2e tests in a separate repo, or do they need to sit in main kubernetes one? @kubernetes/test-infra-maintainers 

cc @timothysc @wojtek-t

**Comment by timothysc** [comment]
We should modify upstream to be less of a thunk and more of a library friendly design such that we can pull in what we need and move those tests out. 

/cc @jayunit100 @jeremyeder

**Comment by spxtr** [comment]
I would like e2e tests in a separate repo. There are some strong arguments against it, however. Now that we have a client repo I think it's much more feasible.

**Comment by timothysc** [comment]
@spxtr I don't see how you can decouple a feature addition and a associated e2e as a pre-req on some PRs..

**Comment by spxtr** [comment]
You add your feature to the main repo, along with thorough unit/integration tests. Then, you add a simple e2e test to the e2e repo. We'd need some way of saying "this e2e test should only pass on this version and later". This sort of layout would make a whole lot of our current problems disappear. Notably, upgrade testing would be *so* much easier.

Anyway, that's a bit off topic. For the question in this issue, I would like to make it easier, but for now it will be a little tricky. You can duplicate what we do in `test/e2e/e2e_test.go` and `test/e2e/e2e.go` along with the nastiness in `hack/ginkgo_e2e.sh`. If you do that and vendor kubernetes, then you should be able to run your tests from another repo, or tie them in to CI so that we can run them for you.

That's super gross, and I wouldn't recommend it at all.

**Comment by timothysc** [comment]
Let's bring this up as a topic for @kubernetes/sig-testing too.
