### ISSUE TITLE
Scalability presubmits should use boskos to manager resources

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#650]
See https://github.com/kubernetes/kubernetes/issues/78701#issuecomment-511569099

**Comment by wojtek-t** [comment]
I think that is only about kubemark - gce-100 should already be using boskos (we're using projects from some pool).

kubemark-500 is more tricky, because currently we have one large project with big quota. We would need to split it to N projects with high enough quota to satisfy the requirements of kubemark-500.

**Comment by mm4tt** [comment]
gce-100 doesn't seem to be using boskos - https://github.com/kubernetes/test-infra/blob/69c1cc687bb70176421e107d4838bf070dc561ea/config/jobs/kubernetes/sig-scalability/sig-scalability-presubmit-jobs.yaml#L29
Or am I missing something?

**Comment by wojtek-t** [comment]
Ohh - interesting. I think we were using, but I must be wrong.

**Comment by wojtek-t** [comment]
So basically the effort here would be to split those project into N with high enough quota to run a single test.

**Comment by oxddr** [comment]
Data point: https://github.com/kubernetes/perf-tests/pull/784 and https://github.com/kubernetes/perf-tests/pull/785 has failed `pull-perf-tests-clusterloader2` due to lack of CPU quota. At the moment we east all of it (2500 CPUs).
