### ISSUE TITLE
CL2 Feature Idea: command line override

### ISSUE THREAD

**Issue by hantaowang** [kubernetes/perf-tests#696]
I'd like to recommend adding functionality to manually set overrides from the command, like how helm allows both the `--values` and `--set` flags.

This would mean `cl2 --testconfig config.yaml --testoverride override.yaml --set "v1=k1,v2=k2"` would take config.yaml, apply the overrides in override.yaml, and then apply the overrides from set.

This would allow more flexibility in tests where using the override is not enough. For example, for storage one override is use to select the storage type and then another to select the test type. But depending on which storage with which test, the SLOs may be different. max_vols_per_pod will have a different SLO for emptydir and for pvcs, so having a command line override will reduce the complexity of needing to specify a third (storage, test) tuple specific SLO.

@wojtek-t @davidz627 @verult @jingxu97

**Comment by wojtek-t** [comment]
I think I disagree.
Your request is pretty similar to what is possible in test-infra:
- you can either use presets (in our case: overrides)
- or you can use --env in test config (in our case: what you're proposing)

This was causing us a bunch of pain in the past because we thought we are setting something via preset and in fact we didn't because it was overrwritten in jobs description.
While this seems tempting from the first glance (becase you may avoid some additional files), I don't think it really buys us anything.

**Comment by hantaowang** [comment]
Alright, I think that is pretty reasonable and I did not think about debugability. I will close this issue then.
